// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QUJmfY6AKyaDl3UWA_H5JCzQEu2ezhQ',
    appId: '1:794235708814:web:e6d99b8ac93ba136dff0df',
    messagingSenderId: '794235708814',
    projectId: 'studytodo-50b0a',
    authDomain: 'studytodo-50b0a.firebaseapp.com',
    storageBucket: 'studytodo-50b0a.firebasestorage.app',
    measurementId: 'G-R4CYKB4MNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb-bWVtYaaNzGsc8oeUXKaPI73ZhmACtA',
    appId: '1:794235708814:android:02ff3b41b5db6ddcdff0df',
    messagingSenderId: '794235708814',
    projectId: 'studytodo-50b0a',
    storageBucket: 'studytodo-50b0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNBU3lVRl57XPqGAKUyssXmUYDtlNV3xM',
    appId: '1:794235708814:ios:e0f8742b434f3c76dff0df',
    messagingSenderId: '794235708814',
    projectId: 'studytodo-50b0a',
    storageBucket: 'studytodo-50b0a.firebasestorage.app',
    iosBundleId: 'com.example.studytodoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNBU3lVRl57XPqGAKUyssXmUYDtlNV3xM',
    appId: '1:794235708814:ios:e0f8742b434f3c76dff0df',
    messagingSenderId: '794235708814',
    projectId: 'studytodo-50b0a',
    storageBucket: 'studytodo-50b0a.firebasestorage.app',
    iosBundleId: 'com.example.studytodoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_QUJmfY6AKyaDl3UWA_H5JCzQEu2ezhQ',
    appId: '1:794235708814:web:a55177620123ffd6dff0df',
    messagingSenderId: '794235708814',
    projectId: 'studytodo-50b0a',
    authDomain: 'studytodo-50b0a.firebaseapp.com',
    storageBucket: 'studytodo-50b0a.firebasestorage.app',
    measurementId: 'G-X8P3HW8ERQ',
  );
}
